version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/backend/nginx
    ports:
      - "8080:8080"
    volumes:
      - webcontent:/var/www/html
    restart: always
    env_file: .env
    depends_on:
      - django
    networks: 
      - transcendence_net

  postgres:
    container_name: postgres
    image: bitnami/postgresql:16.2.0-debian-12-r8
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - transcendence_net
    restart: unless-stopped

  django:
    container_name: django
    build:
      context: ./requirements/backend/django
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - ./requirements/backend/django:/app
    ports:
      - "8000:8000"
    networks:
      - transcendence_net


volumes:
  webcontent:
    name: webcontent
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/webcontent
      o: bind

  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/db_volume
      o: bind


networks:
  transcendence_net:
    name: transcendence_net
    driver: bridge